# LambdaTest Configuration

# Project and folder configuration
project_id: "01KS5W8F42SKE9CZDFMW7AWT47"
folder_id: "e004d04a-4f9b-4bd7-b4e7-7a95eea984d0"

# Test Run configuration
assignee: 41319
environment_id: 270266

# Test URL for automation
test_url: "https://demo.lambdatestinternal.com"
allowed_triggers:
  - onPullRequestOpened
  - onComment
